const fs = require('fs');
const path = require('path');

/**
 * Скрипт для генерации типов для i18n
 */
function generateI18nTypes() {
  console.log('🚀 Generating i18n types...');

  const localesPath = path.join(process.cwd(), 'src', 'core', 'i18n', 'locales');
  const outputPath = path.join(
    process.cwd(),
    'src',
    'core',
    'i18n',
    'generated',
    'i18n.generated.ts',
  );

  // Создаем папку generated если её нет
  const generatedDir = path.dirname(outputPath);
  if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
    console.log(`📁 Created directory: ${generatedDir}`);
  }

  // Проверяем существование папки с переводами
  if (!fs.existsSync(localesPath)) {
    console.error('❌ Locales directory not found:', localesPath);
    process.exit(1);
  }

  // Читаем структуру JSON файлов и генерируем типы
  const enPath = path.join(localesPath, 'en');

  if (!fs.existsSync(enPath)) {
    console.error('❌ English locales directory not found:', enPath);
    process.exit(1);
  }

  const namespaceFiles = fs.readdirSync(enPath).filter((file) => file.endsWith('.json'));

  if (namespaceFiles.length === 0) {
    console.error('❌ No JSON translation files found in:', enPath);
    process.exit(1);
  }

  console.log(`📝 Found namespaces: ${namespaceFiles.join(', ')}`);

  let typesContent = `/* DO NOT EDIT, file generated by custom script */
import { Path } from "nestjs-i18n";

export type I18nTranslations = {\n`;

  for (const namespaceFile of namespaceFiles) {
    const namespace = namespaceFile.replace('.json', '');
    const filePath = path.join(enPath, namespaceFile);

    try {
      const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      typesContent += `  ${namespace}: ${generateInterface(content, 2)};\n`;
      console.log(`✅ Processed namespace: ${namespace}`);
    } catch (error) {
      console.error(`❌ Error processing ${namespaceFile}:`, error.message);
      process.exit(1);
    }
  }

  typesContent += `};\n\n`;

  // === ДОБАВЛЕНО: генерация I18N_NAMESPACES ===
  const namespaceNames = namespaceFiles.map((file) => file.replace('.json', ''));
  typesContent += `export const I18N_NAMESPACES = [\n`;
  namespaceNames.forEach((ns) => {
    typesContent += `  '${ns}',\n`;
  });
  typesContent += `] as const;\n\n`;

  typesContent += `export type I18nNamespace = typeof I18N_NAMESPACES[number];\n\n`;
  // === КОНЕЦ ДОБАВЛЕНИЯ ===

  typesContent += `export type I18nPath = Path<I18nTranslations>;\n`;

  fs.writeFileSync(outputPath, typesContent);
  console.log('✅ i18n types generated successfully!');
  console.log(`📄 Output file: ${outputPath}`);
}

function generateInterface(obj, indent) {
  const spaces = ' '.repeat(indent);
  let result = '{\n';

  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      result += `${spaces}  ${key}: ${generateInterface(value, indent + 2)},\n`;
    } else {
      result += `${spaces}  ${key}: string;\n`;
    }
  }

  result += `${spaces}}`;
  return result;
}

// Запускаем генерацию
generateI18nTypes();
